package main

const (
	TABLE_SIZE = 70
	PRIVATE_VECTOR_SIZE = 10
	TABLE_PRIME_SIZE = 8
	PRIVATE_VECTOR_PRIME_SIZE = 2
	E_VALUE = 11
	M_VALUE = 52
	DELTA_VALUE = 0x3FB70A3D70A3D70A
	NUM_INSTANCES = 64
	EVAL_MODE = "table"
	ACTIVATION = "gelu"
	PROVING = true
	VALUES_DIR = "y_yprime_examples_mini_resnet_act_act2"
	SIZE_VALUE = 12
)
